services:
  - type: web
    name: spotter-trip-planner-api
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn trip_planner.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
